conn sys/oracle as sysdba;
create user options identified by admin;
grant unlimited tablespace to options;
grant all privileges to options;
GRANT SELECT ON ALL_SEQUENCES to options;
GRANT SELECT ON ALL_OBJECTS to options;
GRANT SELECT ON DBA_SEQUENCES to options;
GRANT SELECT ON DBA_OBJECTS to options;
CREATE TABLESPACE T01 DATAFILE '/u01/app/oracle/oradata/XE/T01.dbf' SIZE 100M;
create user options_test identified by admintest;
grant unlimited tablespace to options_test;
grant all privileges to options_test;
GRANT SELECT ON ALL_SEQUENCES to options_test;
GRANT SELECT ON ALL_OBJECTS to options_test;
GRANT SELECT ON DBA_SEQUENCES to options_test;
GRANT SELECT ON DBA_OBJECTS to options_test;
CREATE TABLESPACE T02 DATAFILE '/u01/app/oracle/oradata/XE/T02.dbf' SIZE 100M;
alter system set processes=300 scope=spfile;
alter system set sessions=300 scope=spfile;
shutdown immediate;
startup;
disc;
conn options/admin;
create role OPTIONS_DELETE;
create role OPTIONS_INSERT;
create role OPTIONS_UPDATE;
create role OPTIONS_SELECT;
create user options_user identified by user;
grant create session to options_user;
grant OPTIONS_DELETE to options_user;
grant OPTIONS_INSERT to options_user;
grant OPTIONS_UPDATE to options_user;
grant OPTIONS_SELECT to options_user;
disc;
conn options_test/admintest;
create role OPTIONS_TEST_DELETE;
create role OPTIONS_TEST_INSERT;
create role OPTIONS_TEST_UPDATE;
create role OPTIONS_TEST_SELECT;
create user options_test_user identified by user;
grant create session to options_test_user;
grant OPTIONS_TEST_DELETE to options_test_user;
grant OPTIONS_TEST_INSERT to options_test_user;
grant OPTIONS_TEST_UPDATE to options_test_user;
grant OPTIONS_TEST_SELECT to options_test_user;
disc;
exit;