CREATE TABLE "OPTIONS_MASTER" (
  "MID" NUMBER(19,0) NOT NULL PRIMARY KEY,
  "MESSAGE" CLOB,
  "DESTINATION" VARCHAR2(255 CHAR),
  "MESSAGE_TYPE" VARCHAR2(255 CHAR),
  "CREATED_DATE" TIMESTAMP (6),
  "UPDATED_DATE" TIMESTAMP (6)
);

CREATE TABLE "OPTIONS_TRAN" (
  "TID" NUMBER(19,0) NOT NULL PRIMARY KEY,
  "MID" NUMBER(19,0),
  "MESSAGE" CLOB,
  "CREATED_DATE" TIMESTAMP (6),
  "UPDATED_DATE" TIMESTAMP (6)
);